// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/file_service.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Bioskynet.Services {
  public static class FileService
  {
    static readonly string __ServiceName = "Bioskynet.Services.FileService";

    static readonly Marshaller<global::Bioskynet.Services.EmptyMessage> __Marshaller_EmptyMessage = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bioskynet.Services.EmptyMessage.Parser.ParseFrom);
    static readonly Marshaller<global::Bioskynet.Services.HelloRequest> __Marshaller_HelloRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bioskynet.Services.HelloRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Bioskynet.Services.HelloReply> __Marshaller_HelloReply = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bioskynet.Services.HelloReply.Parser.ParseFrom);
    static readonly Marshaller<global::Bioskynet.Services.FileMessage> __Marshaller_FileMessage = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bioskynet.Services.FileMessage.Parser.ParseFrom);
    static readonly Marshaller<global::Bioskynet.Services.FileBytes> __Marshaller_FileBytes = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bioskynet.Services.FileBytes.Parser.ParseFrom);
    static readonly Marshaller<global::Bioskynet.Services.ExistMessage> __Marshaller_ExistMessage = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bioskynet.Services.ExistMessage.Parser.ParseFrom);

    static readonly Method<global::Bioskynet.Services.EmptyMessage, global::Bioskynet.Services.EmptyMessage> __Method_Heartbeat = new Method<global::Bioskynet.Services.EmptyMessage, global::Bioskynet.Services.EmptyMessage>(
        MethodType.Unary,
        __ServiceName,
        "Heartbeat",
        __Marshaller_EmptyMessage,
        __Marshaller_EmptyMessage);

    static readonly Method<global::Bioskynet.Services.HelloRequest, global::Bioskynet.Services.HelloReply> __Method_SayHello = new Method<global::Bioskynet.Services.HelloRequest, global::Bioskynet.Services.HelloReply>(
        MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    static readonly Method<global::Bioskynet.Services.FileMessage, global::Bioskynet.Services.FileBytes> __Method_GetFile = new Method<global::Bioskynet.Services.FileMessage, global::Bioskynet.Services.FileBytes>(
        MethodType.Unary,
        __ServiceName,
        "GetFile",
        __Marshaller_FileMessage,
        __Marshaller_FileBytes);

    static readonly Method<global::Bioskynet.Services.FileBytes, global::Bioskynet.Services.FileMessage> __Method_CreateFile = new Method<global::Bioskynet.Services.FileBytes, global::Bioskynet.Services.FileMessage>(
        MethodType.Unary,
        __ServiceName,
        "CreateFile",
        __Marshaller_FileBytes,
        __Marshaller_FileMessage);

    static readonly Method<global::Bioskynet.Services.FileMessage, global::Bioskynet.Services.EmptyMessage> __Method_DeleteFile = new Method<global::Bioskynet.Services.FileMessage, global::Bioskynet.Services.EmptyMessage>(
        MethodType.Unary,
        __ServiceName,
        "DeleteFile",
        __Marshaller_FileMessage,
        __Marshaller_EmptyMessage);

    static readonly Method<global::Bioskynet.Services.FileMessage, global::Bioskynet.Services.ExistMessage> __Method_FileExists = new Method<global::Bioskynet.Services.FileMessage, global::Bioskynet.Services.ExistMessage>(
        MethodType.Unary,
        __ServiceName,
        "FileExists",
        __Marshaller_FileMessage,
        __Marshaller_ExistMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Bioskynet.Services.FileServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FileService</summary>
    public abstract class FileServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Bioskynet.Services.EmptyMessage> Heartbeat(global::Bioskynet.Services.EmptyMessage request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///    option (google.api.http).get = "/v1/hello/{name}";
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Bioskynet.Services.HelloReply> SayHello(global::Bioskynet.Services.HelloRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bioskynet.Services.FileBytes> GetFile(global::Bioskynet.Services.FileMessage request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bioskynet.Services.FileMessage> CreateFile(global::Bioskynet.Services.FileBytes request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bioskynet.Services.EmptyMessage> DeleteFile(global::Bioskynet.Services.FileMessage request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bioskynet.Services.ExistMessage> FileExists(global::Bioskynet.Services.FileMessage request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FileService</summary>
    public class FileServiceClient : ClientBase<FileServiceClient>
    {
      /// <summary>Creates a new client for FileService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FileServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FileService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FileServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FileServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FileServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Bioskynet.Services.EmptyMessage Heartbeat(global::Bioskynet.Services.EmptyMessage request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Heartbeat(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bioskynet.Services.EmptyMessage Heartbeat(global::Bioskynet.Services.EmptyMessage request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Heartbeat, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.EmptyMessage> HeartbeatAsync(global::Bioskynet.Services.EmptyMessage request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return HeartbeatAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.EmptyMessage> HeartbeatAsync(global::Bioskynet.Services.EmptyMessage request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Heartbeat, null, options, request);
      }
      /// <summary>
      ///    option (google.api.http).get = "/v1/hello/{name}";
      /// </summary>
      public virtual global::Bioskynet.Services.HelloReply SayHello(global::Bioskynet.Services.HelloRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHello(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///    option (google.api.http).get = "/v1/hello/{name}";
      /// </summary>
      public virtual global::Bioskynet.Services.HelloReply SayHello(global::Bioskynet.Services.HelloRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>
      ///    option (google.api.http).get = "/v1/hello/{name}";
      /// </summary>
      public virtual AsyncUnaryCall<global::Bioskynet.Services.HelloReply> SayHelloAsync(global::Bioskynet.Services.HelloRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///    option (google.api.http).get = "/v1/hello/{name}";
      /// </summary>
      public virtual AsyncUnaryCall<global::Bioskynet.Services.HelloReply> SayHelloAsync(global::Bioskynet.Services.HelloRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual global::Bioskynet.Services.FileBytes GetFile(global::Bioskynet.Services.FileMessage request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetFile(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bioskynet.Services.FileBytes GetFile(global::Bioskynet.Services.FileMessage request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFile, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.FileBytes> GetFileAsync(global::Bioskynet.Services.FileMessage request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetFileAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.FileBytes> GetFileAsync(global::Bioskynet.Services.FileMessage request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFile, null, options, request);
      }
      public virtual global::Bioskynet.Services.FileMessage CreateFile(global::Bioskynet.Services.FileBytes request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateFile(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bioskynet.Services.FileMessage CreateFile(global::Bioskynet.Services.FileBytes request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateFile, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.FileMessage> CreateFileAsync(global::Bioskynet.Services.FileBytes request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateFileAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.FileMessage> CreateFileAsync(global::Bioskynet.Services.FileBytes request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateFile, null, options, request);
      }
      public virtual global::Bioskynet.Services.EmptyMessage DeleteFile(global::Bioskynet.Services.FileMessage request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteFile(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bioskynet.Services.EmptyMessage DeleteFile(global::Bioskynet.Services.FileMessage request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteFile, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.EmptyMessage> DeleteFileAsync(global::Bioskynet.Services.FileMessage request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteFileAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.EmptyMessage> DeleteFileAsync(global::Bioskynet.Services.FileMessage request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteFile, null, options, request);
      }
      public virtual global::Bioskynet.Services.ExistMessage FileExists(global::Bioskynet.Services.FileMessage request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return FileExists(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bioskynet.Services.ExistMessage FileExists(global::Bioskynet.Services.FileMessage request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FileExists, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.ExistMessage> FileExistsAsync(global::Bioskynet.Services.FileMessage request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return FileExistsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Bioskynet.Services.ExistMessage> FileExistsAsync(global::Bioskynet.Services.FileMessage request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FileExists, null, options, request);
      }
      protected override FileServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FileServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(FileServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Heartbeat, serviceImpl.Heartbeat)
          .AddMethod(__Method_SayHello, serviceImpl.SayHello)
          .AddMethod(__Method_GetFile, serviceImpl.GetFile)
          .AddMethod(__Method_CreateFile, serviceImpl.CreateFile)
          .AddMethod(__Method_DeleteFile, serviceImpl.DeleteFile)
          .AddMethod(__Method_FileExists, serviceImpl.FileExists).Build();
    }

  }
}
#endregion
